2024-09-10 11:13:15,798 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:15,855 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:15,876 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:16,564 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:16,655 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:16,686 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:17,475 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:17,609 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:17,620 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:18,255 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:18,384 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:18,397 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:19,153 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:19,293 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:19,375 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:19,915 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:20,086 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:20,177 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:20,799 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:20,983 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:21,116 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:21,561 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:21,756 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:21,885 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:22,461 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:22,664 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:22,839 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:23,225 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:23,471 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:23,608 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:24,119 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:24,392 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:24,557 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:24,876 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:25,158 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:25,334 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:25,785 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:26,067 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:26,310 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:26,547 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:26,838 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:27,081 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:27,442 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:27,762 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:28,051 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:28,206 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:28,533 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:28,821 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:29,439 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:29,773 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:30,329 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:30,700 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:31,125 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:31,481 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:32,044 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:32,426 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:32,829 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:33,208 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:33,730 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:34,157 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:34,529 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:34,947 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:35,416 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:35,869 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:57,636 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:58,521 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:13:59,300 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:14:00,199 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:14:05,731 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:11,236 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:13,327 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:15,425 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:17,532 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:18,895 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:19,612 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:20,933 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:21,874 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:23,024 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:23,961 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:25,092 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:27,206 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:29,242 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:29,289 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:31,559 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:33,637 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:34,538 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:35,720 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:37,795 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:39,774 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:39,876 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:41,943 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:42,563 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:44,554 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:45,000 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:46,020 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:46,595 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:48,040 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:48,609 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:49,210 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:50,075 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:50,352 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:50,649 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:51,210 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:52,112 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:52,700 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:53,271 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:54,304 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:54,896 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:55,320 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:55,585 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:56,317 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:56,915 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:57,374 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:58,373 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:58,951 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:14:59,406 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:00,385 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:00,977 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:01,160 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:01,205 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:01,847 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:02,455 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:03,265 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:03,273 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:03,864 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:04,518 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:05,282 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:05,361 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:06,330 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:06,740 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:07,405 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:07,516 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:08,473 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:08,774 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:09,481 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:09,553 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:10,528 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:10,844 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:11,632 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:11,712 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:12,729 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:12,883 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:13,660 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:14,763 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:14,953 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:16,781 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:16,975 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:18,815 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:19,177 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:20,855 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:21,222 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:22,869 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:23,277 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:25,325 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:26,470 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.aerosol_aeronet_driver
2024-09-10 11:15:27,430 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.aerosol_aeronet_driver
2024-09-10 11:15:29,456 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:30,579 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.aerosol_budget_driver
2024-09-10 11:15:31,626 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.lat_lon_driver
2024-09-10 11:15:33,578 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.aerosol_budget_driver
2024-09-10 11:15:47,159 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.arm_diags_driver
2024-09-10 11:15:50,932 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.arm_diags_driver
2024-09-10 11:15:54,600 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.arm_diags_driver
2024-09-10 11:15:57,802 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.tc_analysis_driver
2024-09-10 11:15:58,189 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.arm_diags_driver
2024-09-10 11:15:58,814 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.aerosol_aeronet_driver
2024-09-10 11:15:59,956 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.aerosol_aeronet_driver
2024-09-10 11:16:41,858 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.arm_diags_driver
2024-09-10 11:17:37,157 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.arm_diags_driver
2024-09-10 11:17:41,415 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.arm_diags_driver
2024-09-10 11:17:45,314 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.arm_diags_driver
2024-09-10 11:18:06,872 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.arm_diags_driver
2024-09-10 11:18:19,358 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.diurnal_cycle_driver
2024-09-10 11:18:19,568 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.diurnal_cycle_driver
2024-09-10 11:18:19,756 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.diurnal_cycle_driver
2024-09-10 11:18:19,929 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.diurnal_cycle_driver
2024-09-10 11:18:20,101 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.diurnal_cycle_driver
2024-09-10 11:18:20,275 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.diurnal_cycle_driver
2024-09-10 11:18:20,450 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.diurnal_cycle_driver
2024-09-10 11:18:20,625 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.diurnal_cycle_driver
2024-09-10 11:18:31,790 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.arm_diags_driver
2024-09-10 11:18:36,168 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.arm_diags_driver
2024-09-10 11:18:40,658 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.arm_diags_driver
2024-09-10 11:18:51,013 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.diurnal_cycle_driver
2024-09-10 11:18:51,373 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.diurnal_cycle_driver
2024-09-10 11:18:51,540 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.diurnal_cycle_driver
2024-09-10 11:18:55,483 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.diurnal_cycle_driver
2024-09-10 11:18:55,680 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.diurnal_cycle_driver
2024-09-10 11:18:55,857 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.diurnal_cycle_driver
2024-09-10 11:18:56,029 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.diurnal_cycle_driver
2024-09-10 11:18:56,245 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.diurnal_cycle_driver
2024-09-10 11:18:56,419 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.diurnal_cycle_driver
2024-09-10 11:18:56,601 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.diurnal_cycle_driver
2024-09-10 11:18:56,784 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.diurnal_cycle_driver
2024-09-10 11:18:56,961 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.diurnal_cycle_driver
2024-09-10 11:18:57,137 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.diurnal_cycle_driver
2024-09-10 11:18:57,309 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.diurnal_cycle_driver
2024-09-10 11:18:57,488 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.diurnal_cycle_driver
2024-09-10 11:18:58,506 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.enso_diags_driver
2024-09-10 11:18:59,394 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.enso_diags_driver
2024-09-10 11:18:59,822 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.arm_diags_driver
2024-09-10 11:19:00,977 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.enso_diags_driver
2024-09-10 11:19:01,921 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.enso_diags_driver
2024-09-10 11:19:03,748 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.diurnal_cycle_driver
2024-09-10 11:19:03,914 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.diurnal_cycle_driver
2024-09-10 11:19:03,962 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.streamflow_driver
2024-09-10 11:19:14,766 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:19:20,003 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:19:25,064 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:19:30,254 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:19:32,203 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.area_mean_time_series_driver
2024-09-10 11:19:35,907 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:19:41,166 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:19:47,059 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:19:52,603 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:19:58,744 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:20:03,923 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:20:04,041 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.enso_diags_driver
2024-09-10 11:20:10,283 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:20:13,090 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.qbo_driver
2024-09-10 11:20:15,571 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:20:15,916 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:20:16,648 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.enso_diags_driver
2024-09-10 11:20:17,507 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.enso_diags_driver
2024-09-10 11:20:18,401 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.enso_diags_driver
2024-09-10 11:20:21,220 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:20:24,141 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:20:27,246 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:20:29,434 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:20:32,551 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:20:34,632 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:20:35,688 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.enso_diags_driver
2024-09-10 11:20:36,440 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.enso_diags_driver
2024-09-10 11:20:37,157 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.enso_diags_driver
2024-09-10 11:20:37,840 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:20:37,871 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.enso_diags_driver
2024-09-10 11:20:38,580 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:20:38,695 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.enso_diags_driver
2024-09-10 11:20:39,516 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.enso_diags_driver
2024-09-10 11:20:39,948 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:20:40,321 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.enso_diags_driver
2024-09-10 11:20:41,063 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.enso_diags_driver
2024-09-10 11:20:43,137 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:20:45,193 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:20:48,378 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:20:48,468 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:20:50,486 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:20:53,838 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:20:53,885 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:20:55,792 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:20:59,207 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:21:01,062 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:21:40,105 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:21:49,412 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:21:50,807 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:21:54,207 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:21:56,252 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:21:58,305 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:21:58,977 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:22:01,479 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:22:04,082 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.annual_cycle_zonal_mean_driver
2024-09-10 11:22:04,869 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:22:08,021 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:22:11,456 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:22:12,703 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:22:13,497 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:22:14,861 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:22:15,549 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:22:18,957 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:22:22,326 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:22:25,561 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:22:27,266 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:22:29,106 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:22:29,392 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:22:31,202 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:22:31,536 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:22:33,298 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:22:33,652 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:22:36,697 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:22:36,890 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:22:39,917 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:22:40,321 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:22:43,290 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:22:43,548 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:22:46,631 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:22:47,074 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:22:59,666 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:03,202 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:05,248 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:07,286 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:18,733 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:20,748 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:22,968 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:25,011 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:25,883 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:27,052 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:27,930 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:29,059 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:29,990 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:31,125 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:32,025 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:33,155 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:34,108 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:35,213 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:36,194 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:37,229 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:38,535 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:39,274 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:40,652 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:41,285 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:42,750 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:43,362 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:44,892 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:45,608 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:47,056 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:47,663 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:49,147 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:49,703 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:51,248 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:51,761 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:53,319 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:53,798 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:55,412 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:55,867 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:57,677 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:57,884 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:23:59,947 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:02,131 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:04,448 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:06,525 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:08,696 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:10,619 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:10,752 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:12,702 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:12,866 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:14,762 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:14,947 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:16,791 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:17,061 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:18,844 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:19,216 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:21,015 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:21,302 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:23,200 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:23,384 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:25,348 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:25,674 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:27,513 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:27,807 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:29,859 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:29,895 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:31,981 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:32,014 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:34,178 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:38,386 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:38,433 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:40,422 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:40,546 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:42,482 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:42,695 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:44,516 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:44,800 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:56,466 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:24:58,479 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:25:00,538 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:25:02,587 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:25:04,647 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:25:06,710 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:25:08,543 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:25:08,756 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:25:10,738 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:25:10,825 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:25:12,927 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:25:15,075 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:25:17,285 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:25:19,453 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:25:21,627 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:25:23,843 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:25:24,409 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:25:26,492 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.polar_driver
2024-09-10 11:29:02,606 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
2024-09-10 11:29:03,543 [ERROR]: core_parameter.py(_run_diag:343) >> Error in e3sm_diags.driver.zonal_mean_xy_driver
AttributeError: 'DataArray' object has no attribute 'units'
FileNotFoundError: [Errno 2] No such file or directory: '/global/cfs/cdirs/e3sm/diagnostics/observations/Atm/tc-analysis/cyclones_hist__1979_2018.nc'
KeyError: 'area'
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/global/cfs/cdirs/e3sm/diagnostics/observations/Atm/tc-analysis/cyclones_hist__1979_2018.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), '19d42650-69de-479f-97dd-c5824c8d3a76']
KeyError: "No variable named 'area'. Variables on the dataset include ['bc_DDF', 'lat_bnds', 'lon_bnds', 'P0', 'PS', ..., 'cosp_sr', 'cosp_tau', 'cosp_tau_modis', 'ilev', 'lev']"
KeyError: 'units'
OSError: No file found for '' and 'ANN' in /global/cfs/cdirs/e3sm/diagnostics/observations/Atm/climatology
OSError: No file found for '' and 'DJF' in /global/cfs/cdirs/e3sm/diagnostics/observations/Atm/climatology
OSError: No file found for '' and 'JJA' in /global/cfs/cdirs/e3sm/diagnostics/observations/Atm/climatology
OSError: No file found for '' and 'MAM' in /global/cfs/cdirs/e3sm/diagnostics/observations/Atm/climatology
OSError: No file found for '' and 'SON' in /global/cfs/cdirs/e3sm/diagnostics/observations/Atm/climatology
OSError: No files found for target variable CLDHGH or derived variables ([('CLDHGH',)]) in /global/cfs/cdirs/e3sm/diagnostics/observations/Atm/time-series/.
OSError: No files found for target variable CLDLOW or derived variables ([('CLDLOW',)]) in /global/cfs/cdirs/e3sm/diagnostics/observations/Atm/time-series/.
OSError: No files found for target variable CLDMED or derived variables ([('CLDMED',)]) in /global/cfs/cdirs/e3sm/diagnostics/observations/Atm/time-series/.
OSError: No files found for target variable CLDTOT or derived variables ([('clt',), ('CLDTOT',)]) in /global/cfs/cdirs/e3sm/diagnostics/observations/Atm/time-series/.
OSError: No files found for target variable FLNS or derived variables ([('sfc_net_lw_all_mon',), ('rlds', 'rlus')]) in /global/cfs/cdirs/e3sm/diagnostics/observations/Atm/time-series/.
OSError: No files found for target variable FSNS or derived variables ([('sfc_net_sw_all_mon',), ('rsds', 'rsus')]) in /global/cfs/cdirs/e3sm/diagnostics/observations/Atm/time-series/.
OSError: No files found for target variable LHFLX or derived variables ([('hfls',), ('QFLX',), ('surface_upward_latent_heat_flux',)]) in /global/cfs/cdirs/e3sm/diagnostics/observations/Atm/time-series/.
OSError: No files found for target variable NET_FLUX_SRF or derived variables ([('FSNS', 'FLNS', 'QFLX', 'PRECC', 'PRECL', 'PRECSC', 'PRECSL', 'SHFLX'), ('FSNS', 'FLNS', 'LHFLX', 'SHFLX'), ('FSNS', 'FLNS', 'QFLX', 'SHFLX'), ('rsds', 'rsus', 'rlds', 'rlus', 'hfls', 'hfss')]) in /global/cfs/cdirs/e3sm/diagnostics/observations/Atm/time-series/.
OSError: No files found for target variable PRECT or derived variables ([('PRECT',), ('pr',), ('PRECC', 'PRECL'), ('sat_gauge_precip',), ('PrecipLiqSurfMassFlux', 'PrecipIceSurfMassFlux')]) in /global/cfs/cdirs/e3sm/diagnostics/observations/Atm/time-series/.
OSError: No files found for target variable RESTOM or derived variables ([('RESTOA',), ('toa_net_all_mon',), ('FSNT', 'FLNT'), ('SW_flux_dn_at_model_top', 'SW_flux_up_at_model_top', 'LW_flux_up_at_model_top'), ('rtmt',)]) in /global/cfs/cdirs/e3sm/e3sm_diags/postprocessed_e3sm_v2_data_for_e3sm_diags/20210528.v2rc3e.piControl.ne30pg2_EC30to60E2r2.chrysalis/time-series/rgr/.
OSError: No files found for target variable SHFLX or derived variables ([('hfss',), ('surf_sens_flux',)]) in /global/cfs/cdirs/e3sm/diagnostics/observations/Atm/time-series/.
OSError: No files found for target variable TAUX or derived variables ([('tauu',), ('surf_mom_flux_U',)]) in /global/cfs/cdirs/e3sm/diagnostics/observations/Atm/time-series/.
OSError: No files found for target variable TAUY or derived variables ([('tauv',), ('surf_mom_flux_V',)]) in /global/cfs/cdirs/e3sm/diagnostics/observations/Atm/time-series/.
OSError: No files found for target variable U or derived variables ([('ua',), ('U',)]) in /global/cfs/cdirs/e3sm/diagnostics/observations/Atm/time-series/.
OSError: The dataset file has no matching source variables for _ABURDENBC
OSError: The dataset file has no matching source variables for _ABURDENDUST
OSError: The dataset file has no matching source variables for _ABURDENPOM
OSError: The dataset file has no matching source variables for _ABURDENSEASALT
OSError: The dataset file has no matching source variables for _ABURDENSO4
OSError: The dataset file has no matching source variables for _ABURDENSO4_STR
OSError: The dataset file has no matching source variables for _ABURDENSO4_TRO
OSError: The dataset file has no matching source variables for _ABURDENSOA
OSError: The dataset file has no matching source variables for AODMOM
OSError: The dataset file has no matching source variables for AODSO4_STR
OSError: The dataset file has no matching source variables for AODSO4_TRO
OSError: The dataset file has no matching source variables for ERFaci
OSError: The dataset file has no matching source variables for ERFari
OSError: The dataset file has no matching source variables for ERFres
OSError: The dataset file has no matching source variables for in_cloud_cdnc
OSError: The dataset file has no matching source variables for in_cloud_lwp
OSError: The dataset file has no matching source variables for in_grid_cdnc
OSError: The dataset file has no matching source variables for in_grid_lwp
OSError: The dataset file has no matching source variables for _Mass_bc_200
OSError: The dataset file has no matching source variables for _Mass_bc_330
OSError: The dataset file has no matching source variables for _Mass_bc_850
OSError: The dataset file has no matching source variables for _Mass_bc_srf
OSError: The dataset file has no matching source variables for _Mass_dst_200
OSError: The dataset file has no matching source variables for _Mass_dst_330
OSError: The dataset file has no matching source variables for _Mass_dst_850
OSError: The dataset file has no matching source variables for _Mass_dst_srf
OSError: The dataset file has no matching source variables for _Mass_mom_200
OSError: The dataset file has no matching source variables for _Mass_mom_330
OSError: The dataset file has no matching source variables for _Mass_mom_850
OSError: The dataset file has no matching source variables for _Mass_mom_srf
OSError: The dataset file has no matching source variables for _Mass_ncl_200
OSError: The dataset file has no matching source variables for _Mass_ncl_330
OSError: The dataset file has no matching source variables for _Mass_ncl_850
OSError: The dataset file has no matching source variables for _Mass_ncl_srf
OSError: The dataset file has no matching source variables for _Mass_pom_200
OSError: The dataset file has no matching source variables for _Mass_pom_330
OSError: The dataset file has no matching source variables for _Mass_pom_850
OSError: The dataset file has no matching source variables for _Mass_pom_srf
OSError: The dataset file has no matching source variables for _Mass_so4_200
OSError: The dataset file has no matching source variables for _Mass_so4_330
OSError: The dataset file has no matching source variables for _Mass_so4_850
OSError: The dataset file has no matching source variables for _Mass_so4_srf
OSError: The dataset file has no matching source variables for _Mass_soa_200
OSError: The dataset file has no matching source variables for _Mass_soa_330
OSError: The dataset file has no matching source variables for _Mass_soa_850
OSError: The dataset file has no matching source variables for _Mass_soa_srf
    raise AttributeError(
    raise IOError(
    raise KeyError(
    raise KeyError(key)
    raise RuntimeError(
    raise RuntimeError(msg)
    raise TypeError(f'Object of type {o.__class__.__name__} '
RuntimeError: Diurnal cycle of nsac1 at Site: PRECT is not supported yet
RuntimeError: Diurnal cycle of twpc1 at Site: PRECT is not supported yet
RuntimeError: Diurnal cycle of twpc2 at Site: PRECT is not supported yet
RuntimeError: Diurnal cycle of twpc3 at Site: PRECT is not supported yet
RuntimeError: To use a non-GSIM reference, please specify streamflow_param.gauges_path. This might be /global/cfs/cdirs/e3sm/diagnostics/observations/Atm/time-series/GSIM/GSIM_catchment_characteristics_all_1km2.csv
TypeError: Object of type MaskedArray is not JSON serializable
UnboundLocalError: local variable 'cwv_max' referenced before assignment
